server:
  port: 8080

spring:
  application:
    name: SPRING-CLOUD-GATEWAY-SERVER
  cloud:
    gateway:
      routes:
        - id: CURRENCY-CONVERSION-SERVICE
          uri: lb://CURRENCY-CONVERSION-SERVICE
          predicates:
            - Path=/currency-conversion/**
        - id: CURRENCY-EXCHANGE-SERVICE
          uri: lb://CURRENCY-EXCHANGE-SERVICE
          predicates:
            - Path=/currency-exchange/**

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka


#eureka.client.register-with-eureka=true
#eureka.client.fetch-registry=true
#to search other service by name
#spring.cloud.gateway.discovery.locator.enabled=true
#spring.cloud.gateway.discovery.locator.lower-case-service-id=true
#
#spring.cloud.gateway.routes[0].id=currency
#spring.cloud.gateway.routes[0].uri=lb://CURRENCY-EXCHANGE-SERVICE
#spring.cloud.gateway.routes[0].predicates[0]=Path=/currency-exchange/**
##spring.cloud.gateway.routes[1].id=inMateService
##spring.cloud.gateway.routes[1].uri=http://localhost:2006/
##spring.cloud.gateway.routes[1].predicates[0]=Path=/consumer/**